mysite/blog/urls.py
from django.urls import path
from .views import *
from .feeds import LastestPostsFeed

# Asignamos un nombre a la aplicación para poder acceder a sus propiedades
app_name = 'blog'
urlpatterns = [
    # Post views
    path('', post_list, name='post_list'),
    path(
        'tag/<slug:tag_slug>',
        post_list,
        name='post_list_by_tag',
    ),
    # path('', views.PostListView.as_view(), name='post_list'), # Para vistas basadas en clases
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',    # Forma de URL canonica
        post_detail,                                        # Vista controladora
        name='post_detail',                                 # Nombre del template
    ),
    path(
        '<int:post_id>/share/', 
        post_share, 
        name='post_share'
    ),
    path(
        '<int:post_id>/comment/', 
        post_comment, 
        name='post_comment'
    ),
    path(
        'feed/',
        LastestPostsFeed(),
        name='post_feed',
    ),
    path(
        'search/',
        post_search,
        name = 'post_search',
    ),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

# Diccionario con los sitemaps de la aplicación
sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    # Ruta raíz, heredando los URL's de la aplicación 'blog'
    path('', include('blog.urls', namespace='blog')),
    # Ruta para los sitemaps
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name = 'django.contrib.sitemaps.views.sitemap'
    )
]

mysite/blog/models.py
from django.db import models 
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Manager para gestionar posts por estado de publicación
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.PUBLISHED
        )

# Modelo (Tabla) Post para la base de datos
class Post(models.Model):
    """Modelo para post en la base de datos"""
    # Subclase para crear opciones para los campos de la DB
    class Status(models.TextChoices):
        DRAFT     = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title   = models.CharField(max_length=250)
    slug    = models.SlugField(
                        max_length=250,
                        # unique_for_date -> Indica que cada campo 'slug' debe de
                        # ser unico por cada fecha de campo 'publish' 
                        # para que las URL sean unicas
                        unique_for_date='publish', 
                    )
    # Llave foranea que apunta a Modelo User 
    author  = models.ForeignKey(User,
                                on_delete=models.CASCADE,
                                # related_name -> este atributo permite darle un nombre
                                # a la relación entre los dos objetos
                                related_name='blog_posts')

    body    = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    status  = models.CharField(max_length=2,
                              # choises -> Este parametro permite asociar opciones
                              # establecidas en la subclase 'Status', permitiendo
                              # establecer solo las opciones que están en el modelo
                              choices=Status.choices,
                              default=Status.DRAFT)
    
    # Manager's
    objects   = models.Manager()   # El manager por default
    published = PublishedManager() # El manager custom para publicaciones
    tags      = TaggableManager()  # Manager para tags

    class Meta:
        ordering = ['-publish']                # Ordenar descendente
        # Agregar un index a la base de datos para mejorar la busqueda
        # dentro de la DB por publicación
        indexes  = [
            models.Index(fields=['-publish']),
        ]

    # Crear URL canonicas
    def get_absolute_url(self):  
        return reverse(
            # URL apuntando a la vista blog_detail
            'blog:post_detail',          
            # Atributos que formarán parte de la URL
            args = [
                    self.publish.year,
                    self.publish.month,
                    self.publish.day,
                    self.slug
                ]
        )

    def __str__(self):
        return self.title  

# Modelo (tabla) Comment para guardar los comentarios de los usuarios
class Comment(models.Model):
    # LLave foranea para apuntar y relacionar a Modelo Post
    post    = models.ForeignKey(
                        Post,
                        on_delete=models.CASCADE,
                        # related_name -> este atributo permite darle un nombre
                        # a la relación entre los dos objetos
                        related_name='comments'
                    )
    name    = models.CharField(max_length=255)
    email   = models.EmailField()
    body    = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active  = models.BooleanField(default=True)

    class Meta:
        # Orden de manera cronologica
        ordering = ['created']     
        # Index para la base de datos
        indexes = [                
            models.Index(fields=['created']),
        ]
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    '''Modelo para crear un formulario para compartir posts via email'''
    name     = forms.CharField(max_length=25)
    email    = forms.EmailField(required=True)
    to       = forms.EmailField(required=True)
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    '''Modelo para crear un formulario para hacer comentarios en un post'''
    class Meta:
        # Configuramos el modelo del que tomará los campos para el 
        # formulario
        model  = Comment
        # Configuración de los campos de los que se genera el formulario
        fields = ['name', 'email', 'body']

class SearchForm(forms.Form):
    '''Modelo para crear un formulario de busqueda'''
    query = forms.CharField()

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.core.mail import send_mail
from django.db.models import Count
# from django.views.generic import ListView
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, \
                                            TrigramSimilarity

# class PostListView(ListView):
#     """
#     Es una alternativa a la funcion post_list(request)
#     """
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'

# Vista post_list
def post_list(request, tag_slug=None):
    """
    Vista que lista todos los posts en template -> list.html
    """
    # Obtener todos los posts a traves del Manager custom -> published
    post_list = Post.published.all()   
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Paginacion con 3 posts por pagina
    paginator   = Paginator(post_list, 3)            # Creamos objeto de paginacion
    page_number = request.GET.get('page', 1)         # Obetenemos la primera pagina
    # Try para acceder a numero de pagina solicitado a traves del request
    try: 
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # Si page_number es diferente de un int
        posts = paginator.page(1)
    except EmptyPage:
        # Si page_number está fuera de rango
        posts = paginator.page(paginator.num_pages)

    # Finalmente, retornamos los posts hacia el template list.html
    return render(request,
                'blog/post/list.html',
                {'posts': posts, 'tag': tag}
            )

# Vista post_detail
def post_detail(request, year, month, day, post):
    """
    Vista que muestra un post completo en template -> detail.html
    """
    # PRIMERA FORMA
    # try:
    #     post = Post.published.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404("No se encontró el Post :(")
    
    # return render(
    #     request,
    #     'blog/post/detail.html',
    #     {'post': post}
    # )

    # SEGUNDA FORMA
    # Para mostrar los detalles de un post y además con una URL canonica
    # usamos tres parametros, se ingresan en la función que buscará el elemento
    # que coincida con los parametros o si no retorna un error 404 (no encontrado)
    post = get_object_or_404(
        Post,
        status = Post.Status.PUBLISHED,
        slug = post,
        publish__year = year,
        publish__month = month,
        publish__day = day
    )

    # Obteniendo todos los comentarios activos
    # Usando el atributo related_name = 'comments' desde el modelo Comment()
    comments = post.comments.filter(active=True) 

    # Formulario para comentarios de usuarios
    form = CommentForm()

    # Listado de posts similares
    # Recuperamos una lista de los tags asociados al post
    post_tags_ids = post.tags.values_list('id', flat=True)                  
    # Recuperamos los posts que contengan los tags anteriormente recuperados (excluyendo el actual)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                    .exclude(id=post.id)
    
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                    .order_by('-same_tags', '-publish')[:4]



    # Finalmente, retornamos el post a visualizar, los comentarios de ese
    # post y el formulario para plasmarlo en el template detail.html
    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'form': form,
            'similar_posts': similar_posts
        }
    )

# Vista post_share
def post_share(request, post_id):
    """
    Vista que genera formulario para compartir un post via email -> share.html
    """
    # Recuperar el post por ID
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    # Variable para verificar si se ha enviado correctamente el mail
    sent = False
    # Si llega una petición de tipo POST...
    if request.method == 'POST':
        # Enviar formulario
        form = EmailPostForm(request.POST)
        # Si los campos pasan la validación
        if form.is_valid():
            # Obtenemos diccionario con datos del formulario
            data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{data['name']} te recomienda leer {post.title}"
            message = f"Dale una leida a {post.title} en {post_url}\n\n" \
                      f"{data['name']}\'s comments: {data['comments']}"
            send_mail(
                    subject, 
                    message, 
                    'guillermovalverde42@gmail.com',
                    [data['to']]
                )
            # Una vez enviado el mail, confirmamos con la variable sent
            sent = True 
    # Si no hay petición de tipo post, entonces no hay datos que procesar
    else:
        form = EmailPostForm()
    
    # Finalmente se retorna el post compartido, el formulario para dibujar en el template
    # y la variable sent para poder saber si se ha enviado o no el mail
    return render(
        request, 
        'blog/post/share.html', 
        {
            'post': post,
            'form': form,
            'sent': sent
        }
    )

# Vista post_comment
@require_POST
def post_comment(request, post_id):
    """
    Vista que genera formulario para crear comentario en un post -> comment.html
    """
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    # Variable vacia para guardar el comentario
    comment = None
    # Creamos instancia de CommentForm con los datos POST del request
    form = CommentForm(data=request.POST)
    # Si la validación de datos es correcta
    if form.is_valid():
        # Crear un comentario sin guardarlo
        comment = form.save(commit=False)
        # Asignamos el post al comentario
        comment.post = post
        # Ahora si, guardamos el comentario en la DB
        comment.save()
    
    # Finalmente, retornamos el post, el comentario y el formulario para dibujar 
    # en la plantilla comment.html
    return render(
        request,
        'blog/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment
        }
    )

# Vista post_search
def post_search(request):
    """
    Vista que genera formulario para realizar una busqueda (query) -> search.html
    """
    form    = SearchForm()
    query   = None
    results = []

    # Si en el diccionario de la peticion hay una key 'query' Ej. -> {'query': ['iones']}
    if 'query' in request.GET:
        # Crear una instancia del formulario 
        # y se pasa el diccionario con la query
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', config='spanish', weight='A') + \
                            SearchVector('body', config='spanish', weight='B')
            search_query = SearchQuery(query, config='spanish')
            results = Post.published.annotate(
                search = search_vector,
                rank = SearchRank(search_vector, search_query),
            ).filter(rank__gte=0.3).order_by('-rank')

    # if 'query' in request.GET:
    #     form = SearchForm(request.GET)
    #     if form.is_valid():
    #         query = form.cleaned_data['query']
    #         results = Post.published.annotate(
    #             similarity=TrigramSimilarity('title', query),
    #         ).filter(similarity__gt=0.1).order_by('-similarity')
    
    return render(
        request,
        'blog/post/search.html',
        {
            'form': form,
            'query': query,
            'results': results
        }
    )

mysite/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Publicado {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown }}
  <p>
    <a href="{% url "blog:post_share" post.id %}">
      Share this post
    </a>
  </p>

  <h2>Similar Posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    There are no similar posts yet.
  {% endfor %}

  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}
  
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
    {% empty %}
      <p>There are no comments</p>
  {% endfor %}
  {% include 'blog/post/includes/comment_form.html' %}
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
  

  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}

  {% for post in posts %}
  
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
      Tags:
      {% for tag in post.tags.all %}

        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}

      {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}

  {% endfor %}
  {% include "pagination.html" with page=posts %}
  {% comment %} {% include "pagination.html" with page=page_obj %} {% endcomment %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4>
        <a href="{{ post.get_absolute_url }}">
          {{ post.title }}
        </a>
      </h4>
      {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post" novalidate>
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}